# CUSTOM APP
# ======================================================================================================================
qabase:
  webui:
    base-url: "https://www.demoblaze.com"
    browser-type: "chromium"
    viewport-width: 1920
    viewport-height: 1080
    timeout-ms: 10000
    headless: true
    trace-on-failure: true
